### ISSUE TITLE
Use scikit-learn instead of sklearn package

### ISSUE THREAD

**Issue by pansapiens** [ArianeMora/scivae#2]
https://github.com/ArianeMora/scivae/blob/064326b5fc5cba74339320d03c263bf718b18c33/setup.py#L49

Is the [sklearn pypi package](https://pypi.org/project/sklearn/) intentionally used, or did you mean [scikit-learn](https://pypi.org/project/scikit-learn/) ? ie the _package name_ for the popular package which is generally used via `import sklearn` is actually `scikit-learn`.

Seems like things might have worked since `scikit-learn` is likely a dependency of one of the other packages, but the `sklearn` package isn't needed ?

**Comment by ArianeMora** [comment]
Oooh exciting first issue 👍 
Thank you, yes I've updated that thanks for pointing this out! 
Since it's just been me for a while I got a little slack with re-merging feature branches, code should be up-to-date now, if you have any issues with anything else please let me know!
